version: "3.1"

services:

  postgres_db:
    image: postgres:14
    restart: always
    environment:   #Set up postgres database name and password
      PGDATA: /var/lib/postgresql/data/test/

      POSTGRES_PASSWORD: example
      POSTGRES_DB: med_db
      POSTGRES_USER: root
    ports:    # Set up ports exposed for other containers to connect to
      - 5432:5432 
    volumes:
      - ./postgres:/var/lib/postgresql/data/pgdata
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - app-med
    
  python:
    depends_on:
      - postgres_db
    links:
      - postgres_db:postgres_db
    image: python:latest
    restart: always

    build: 
      dockerfile: Dockerfile
    networks:
      - app-med

networks:
  app-med: